# Generated by Django 5.2.13 on 2026-05-01 19:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "CPF",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                (
                    "celular",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="Celular"
                    ),
                ),
                (
                    "contato",
                    models.CharField(blank=True, max_length=11, verbose_name="Contato"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                ("endereco", models.CharField(max_length=100, verbose_name="Endereço")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ADM", "Administrador"),
                            ("COL", "Colaborador"),
                            ("PRP", "Proprietário"),
                            ("CLI", "Cliente"),
                        ],
                        default="CLI",
                        max_length=3,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="usuarios/",
                        verbose_name="Foto",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Chaves",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        primary_key=True, serialize=False, verbose_name="Código"
                    ),
                ),
                (
                    "esta_disponivel",
                    models.BooleanField(default=True, verbose_name="Disponibilidade"),
                ),
                ("data_ação", models.DateTimeField(auto_now=True, verbose_name="Data")),
                (
                    "usuario_açao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
                (
                    "chave",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="gestao.chaves"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Imoveis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=100, verbose_name="Endereço")),
                ("numero", models.CharField(max_length=6, verbose_name="Número")),
                ("bairro", models.CharField(max_length=100, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=100, verbose_name="Estado")),
                (
                    "observacao",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "proprietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FotosImoveis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="imoveis/", verbose_name="Foto"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Descrição"
                    ),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="gestao.imoveis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do Imóvel",
                "verbose_name_plural": "Fotos dos Imóvel",
            },
        ),
        migrations.AddField(
            model_name="chaves",
            name="imovel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestao.imoveis"
            ),
        ),
        migrations.AddConstraint(
            model_name="imoveis",
            constraint=models.UniqueConstraint(
                fields=("rua", "numero", "bairro", "cidade", "estado"), name="endereco"
            ),
        ),
    ]
